# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gabriel.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gabriel.proto',
  package='gabriel',
  syntax='proto3',
  serialized_options=_b('\n\032edu.cmu.cs.gabriel.networkB\006Protos'),
  serialized_pb=_b('\n\rgabriel.proto\x12\x07gabriel\x1a\x19google/protobuf/any.proto\"\x9d\x01\n\nFromClient\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12*\n\x0cpayload_type\x18\x02 \x01(\x0e\x32\x14.gabriel.PayloadType\x12\x13\n\x0b\x65ngine_name\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12+\n\rengine_fields\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\"\xba\x03\n\rResultWrapper\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x03\x12-\n\x06status\x18\x02 \x01(\x0e\x32\x1d.gabriel.ResultWrapper.Status\x12.\n\x07results\x18\x04 \x03(\x0b\x32\x1d.gabriel.ResultWrapper.Result\x12+\n\rengine_fields\x18\x05 \x01(\x0b\x32\x14.google.protobuf.Any\x1aZ\n\x06Result\x12*\n\x0cpayload_type\x18\x01 \x01(\x0e\x32\x14.gabriel.PayloadType\x12\x13\n\x0b\x65ngine_name\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\"\xae\x01\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0fWELCOME_MESSAGE\x10\x01\x12\x15\n\x11UNSPECIFIED_ERROR\x10\x02\x12\x16\n\x12WRONG_INPUT_FORMAT\x10\x03\x12\"\n\x1eREQUESTED_ENGINE_NOT_AVAILABLE\x10\x04\x12\r\n\tNO_TOKENS\x10\x05\x12\x0e\n\nQUEUE_FULL\x10\x06\x12\x10\n\x0c\x45NGINE_ERROR\x10\x07\"N\n\x08ToClient\x12.\n\x0eresult_wrapper\x18\x01 \x01(\x0b\x32\x16.gabriel.ResultWrapper\x12\x12\n\nnum_tokens\x18\x02 \x01(\x05\"\x9a\x01\n\x0cToFromEngine\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12*\n\x0b\x66rom_client\x18\x03 \x01(\x0b\x32\x13.gabriel.FromClientH\x00\x12\x30\n\x0eresult_wrapper\x18\x04 \x01(\x0b\x32\x16.gabriel.ResultWrapperH\x00\x42\x10\n\x0e\x63lient_message*Z\n\x0bPayloadType\x12\t\n\x05IMAGE\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05\x41UDIO\x10\x02\x12\x11\n\rACCELEROMETER\x10\x03\x12\x08\n\x04TEXT\x10\x04\x12\r\n\tANIMATION\x10\x05\x42$\n\x1a\x65\x64u.cmu.cs.gabriel.networkB\x06Protosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_PAYLOADTYPE = _descriptor.EnumDescriptor(
  name='PayloadType',
  full_name='gabriel.PayloadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IMAGE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VIDEO', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUDIO', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACCELEROMETER', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TEXT', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ANIMATION', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=895,
  serialized_end=985,
)
_sym_db.RegisterEnumDescriptor(_PAYLOADTYPE)

PayloadType = enum_type_wrapper.EnumTypeWrapper(_PAYLOADTYPE)
IMAGE = 0
VIDEO = 1
AUDIO = 2
ACCELEROMETER = 3
TEXT = 4
ANIMATION = 5


_RESULTWRAPPER_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='gabriel.ResultWrapper.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WELCOME_MESSAGE', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNSPECIFIED_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WRONG_INPUT_FORMAT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REQUESTED_ENGINE_NOT_AVAILABLE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NO_TOKENS', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='QUEUE_FULL', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENGINE_ERROR', index=7, number=7,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=482,
  serialized_end=656,
)
_sym_db.RegisterEnumDescriptor(_RESULTWRAPPER_STATUS)


_FROMCLIENT = _descriptor.Descriptor(
  name='FromClient',
  full_name='gabriel.FromClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='gabriel.FromClient.frame_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload_type', full_name='gabriel.FromClient.payload_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_name', full_name='gabriel.FromClient.engine_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='gabriel.FromClient.payload', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_fields', full_name='gabriel.FromClient.engine_fields', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=211,
)


_RESULTWRAPPER_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='gabriel.ResultWrapper.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_type', full_name='gabriel.ResultWrapper.Result.payload_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_name', full_name='gabriel.ResultWrapper.Result.engine_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='gabriel.ResultWrapper.Result.payload', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=479,
)

_RESULTWRAPPER = _descriptor.Descriptor(
  name='ResultWrapper',
  full_name='gabriel.ResultWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='gabriel.ResultWrapper.frame_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='gabriel.ResultWrapper.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='gabriel.ResultWrapper.results', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='engine_fields', full_name='gabriel.ResultWrapper.engine_fields', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESULTWRAPPER_RESULT, ],
  enum_types=[
    _RESULTWRAPPER_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=656,
)


_TOCLIENT = _descriptor.Descriptor(
  name='ToClient',
  full_name='gabriel.ToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_wrapper', full_name='gabriel.ToClient.result_wrapper', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_tokens', full_name='gabriel.ToClient.num_tokens', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=736,
)


_TOFROMENGINE = _descriptor.Descriptor(
  name='ToFromEngine',
  full_name='gabriel.ToFromEngine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='gabriel.ToFromEngine.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='gabriel.ToFromEngine.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_client', full_name='gabriel.ToFromEngine.from_client', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result_wrapper', full_name='gabriel.ToFromEngine.result_wrapper', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='client_message', full_name='gabriel.ToFromEngine.client_message',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=739,
  serialized_end=893,
)

_FROMCLIENT.fields_by_name['payload_type'].enum_type = _PAYLOADTYPE
_FROMCLIENT.fields_by_name['engine_fields'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RESULTWRAPPER_RESULT.fields_by_name['payload_type'].enum_type = _PAYLOADTYPE
_RESULTWRAPPER_RESULT.containing_type = _RESULTWRAPPER
_RESULTWRAPPER.fields_by_name['status'].enum_type = _RESULTWRAPPER_STATUS
_RESULTWRAPPER.fields_by_name['results'].message_type = _RESULTWRAPPER_RESULT
_RESULTWRAPPER.fields_by_name['engine_fields'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_RESULTWRAPPER_STATUS.containing_type = _RESULTWRAPPER
_TOCLIENT.fields_by_name['result_wrapper'].message_type = _RESULTWRAPPER
_TOFROMENGINE.fields_by_name['from_client'].message_type = _FROMCLIENT
_TOFROMENGINE.fields_by_name['result_wrapper'].message_type = _RESULTWRAPPER
_TOFROMENGINE.oneofs_by_name['client_message'].fields.append(
  _TOFROMENGINE.fields_by_name['from_client'])
_TOFROMENGINE.fields_by_name['from_client'].containing_oneof = _TOFROMENGINE.oneofs_by_name['client_message']
_TOFROMENGINE.oneofs_by_name['client_message'].fields.append(
  _TOFROMENGINE.fields_by_name['result_wrapper'])
_TOFROMENGINE.fields_by_name['result_wrapper'].containing_oneof = _TOFROMENGINE.oneofs_by_name['client_message']
DESCRIPTOR.message_types_by_name['FromClient'] = _FROMCLIENT
DESCRIPTOR.message_types_by_name['ResultWrapper'] = _RESULTWRAPPER
DESCRIPTOR.message_types_by_name['ToClient'] = _TOCLIENT
DESCRIPTOR.message_types_by_name['ToFromEngine'] = _TOFROMENGINE
DESCRIPTOR.enum_types_by_name['PayloadType'] = _PAYLOADTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FromClient = _reflection.GeneratedProtocolMessageType('FromClient', (_message.Message,), dict(
  DESCRIPTOR = _FROMCLIENT,
  __module__ = 'gabriel_pb2'
  # @@protoc_insertion_point(class_scope:gabriel.FromClient)
  ))
_sym_db.RegisterMessage(FromClient)

ResultWrapper = _reflection.GeneratedProtocolMessageType('ResultWrapper', (_message.Message,), dict(

  Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), dict(
    DESCRIPTOR = _RESULTWRAPPER_RESULT,
    __module__ = 'gabriel_pb2'
    # @@protoc_insertion_point(class_scope:gabriel.ResultWrapper.Result)
    ))
  ,
  DESCRIPTOR = _RESULTWRAPPER,
  __module__ = 'gabriel_pb2'
  # @@protoc_insertion_point(class_scope:gabriel.ResultWrapper)
  ))
_sym_db.RegisterMessage(ResultWrapper)
_sym_db.RegisterMessage(ResultWrapper.Result)

ToClient = _reflection.GeneratedProtocolMessageType('ToClient', (_message.Message,), dict(
  DESCRIPTOR = _TOCLIENT,
  __module__ = 'gabriel_pb2'
  # @@protoc_insertion_point(class_scope:gabriel.ToClient)
  ))
_sym_db.RegisterMessage(ToClient)

ToFromEngine = _reflection.GeneratedProtocolMessageType('ToFromEngine', (_message.Message,), dict(
  DESCRIPTOR = _TOFROMENGINE,
  __module__ = 'gabriel_pb2'
  # @@protoc_insertion_point(class_scope:gabriel.ToFromEngine)
  ))
_sym_db.RegisterMessage(ToFromEngine)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
