# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lego.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lego.proto',
  package='gabriel.lego',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nlego.proto\x12\x0cgabriel.lego\"\xa2\x03\n\tLEGOState\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x36\n\ntimestamps\x18\x02 \x01(\x0b\x32\".gabriel.lego.LEGOState.Timestamps\x12\x34\n\x06result\x18\x03 \x01(\x0e\x32$.gabriel.lego.LEGOState.FRAME_RESULT\x12\x15\n\rtask_finished\x18\x04 \x01(\x08\x12\x1a\n\x12target_state_index\x18\x05 \x01(\x05\x12\x1b\n\x13\x63urrent_state_index\x18\x06 \x01(\x05\x12\x1e\n\x16\x65rror_prev_board_state\x18\x07 \x01(\x0c\x1a,\n\nTimestamps\x12\x10\n\x08received\x18\x01 \x01(\x01\x12\x0c\n\x04sent\x18\x03 \x01(\x01\"x\n\x0c\x46RAME_RESULT\x12\r\n\tNO_CHANGE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0e\n\nTASK_ERROR\x10\x02\x12\x0e\n\nJUNK_FRAME\x10\x03\x12\x18\n\x14LOW_CONFIDENCE_RECON\x10\x04\x12\x12\n\x0eOTHER_CV_ERROR\x10\x05\x62\x06proto3')
)



_LEGOSTATE_FRAME_RESULT = _descriptor.EnumDescriptor(
  name='FRAME_RESULT',
  full_name='gabriel.lego.LEGOState.FRAME_RESULT',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NO_CHANGE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TASK_ERROR', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JUNK_FRAME', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW_CONFIDENCE_RECON', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OTHER_CV_ERROR', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=327,
  serialized_end=447,
)
_sym_db.RegisterEnumDescriptor(_LEGOSTATE_FRAME_RESULT)


_LEGOSTATE_TIMESTAMPS = _descriptor.Descriptor(
  name='Timestamps',
  full_name='gabriel.lego.LEGOState.Timestamps',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='received', full_name='gabriel.lego.LEGOState.Timestamps.received', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sent', full_name='gabriel.lego.LEGOState.Timestamps.sent', index=1,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=325,
)

_LEGOSTATE = _descriptor.Descriptor(
  name='LEGOState',
  full_name='gabriel.lego.LEGOState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='gabriel.lego.LEGOState.task_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamps', full_name='gabriel.lego.LEGOState.timestamps', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='result', full_name='gabriel.lego.LEGOState.result', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='task_finished', full_name='gabriel.lego.LEGOState.task_finished', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target_state_index', full_name='gabriel.lego.LEGOState.target_state_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='current_state_index', full_name='gabriel.lego.LEGOState.current_state_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_prev_board_state', full_name='gabriel.lego.LEGOState.error_prev_board_state', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LEGOSTATE_TIMESTAMPS, ],
  enum_types=[
    _LEGOSTATE_FRAME_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=447,
)

_LEGOSTATE_TIMESTAMPS.containing_type = _LEGOSTATE
_LEGOSTATE.fields_by_name['timestamps'].message_type = _LEGOSTATE_TIMESTAMPS
_LEGOSTATE.fields_by_name['result'].enum_type = _LEGOSTATE_FRAME_RESULT
_LEGOSTATE_FRAME_RESULT.containing_type = _LEGOSTATE
DESCRIPTOR.message_types_by_name['LEGOState'] = _LEGOSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LEGOState = _reflection.GeneratedProtocolMessageType('LEGOState', (_message.Message,), dict(

  Timestamps = _reflection.GeneratedProtocolMessageType('Timestamps', (_message.Message,), dict(
    DESCRIPTOR = _LEGOSTATE_TIMESTAMPS,
    __module__ = 'lego_pb2'
    # @@protoc_insertion_point(class_scope:gabriel.lego.LEGOState.Timestamps)
    ))
  ,
  DESCRIPTOR = _LEGOSTATE,
  __module__ = 'lego_pb2'
  # @@protoc_insertion_point(class_scope:gabriel.lego.LEGOState)
  ))
_sym_db.RegisterMessage(LEGOState)
_sym_db.RegisterMessage(LEGOState.Timestamps)


# @@protoc_insertion_point(module_scope)
