# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lego.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='lego.proto',
    package='gabriel.lego',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\nlego.proto\x12\x0cgabriel.lego\"H\n\tLEGOState\x12\x0c\n\x04task'
        '\x18\x01 \x01(\t\x12\x1a\n\x12target_state_index\x18\x02 \x01('
        '\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x62\x06proto3')
)

_LEGOSTATE = _descriptor.Descriptor(
    name='LEGOState',
    full_name='gabriel.lego.LEGOState',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='task', full_name='gabriel.lego.LEGOState.task', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='target_state_index',
            full_name='gabriel.lego.LEGOState.target_state_index', index=1,
            number=2, type=5, cpp_type=1, label=1,
            has_default_value=False, default_value=0,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
        _descriptor.FieldDescriptor(
            name='timestamp', full_name='gabriel.lego.LEGOState.timestamp',
            index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=28,
    serialized_end=100,
)

DESCRIPTOR.message_types_by_name['LEGOState'] = _LEGOSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LEGOState = _reflection.GeneratedProtocolMessageType('LEGOState',
                                                     (_message.Message,), dict(
        DESCRIPTOR=_LEGOSTATE,
        __module__='lego_pb2'
        # @@protoc_insertion_point(class_scope:gabriel.lego.LEGOState)
    ))
_sym_db.RegisterMessage(LEGOState)

# @@protoc_insertion_point(module_scope)
